@startuml
skinparam defaultFontSize 36

component "EASNFW-SENSOR" as sensor {
    component "sample audio" as sample_audio
    component "sample environmental data" as sample_env
    component "I2S" as i2s
    component "I2C" as i2c
    component "SPIM" as spim
    component "cloud" as cloud
    component "audio processing" as audio_proc
    component "mass storage" as mass_storage
    component "nvs" as nvs
    component "log" as log
    component "self-test" as self_test
    component "cli" as cli
    component "power management" as power_mgmt
}

[Audio sensor] as audio_sensor
[Environmental sensor] as env_sensor
[SD card] as sd_card
[Internal flash] as internal_flash
[Host PC] as host_pc
[EASNFW-CLOUD] as cloud_comp

sample_audio --> i2s
sample_env --> i2c
i2s <--> audio_sensor : I2S
i2c <--> env_sensor : I2C
i2c --> audio_sensor : I2C (configuration)
sample_audio --> audio_proc
audio_proc --> cloud
cloud --> mass_storage
cloud --> spim
mass_storage --> spim
spim <--> sd_card : SPI
spim <--> cloud_comp : SPI
nvs <--> internal_flash
log --> host_pc : Serial-USB
self_test --> sample_audio
self_test --> sample_env
self_test --> i2s
self_test --> i2c
self_test --> spim
self_test --> cloud
self_test --> audio_proc
self_test --> mass_storage
self_test --> nvs
cli --> sample_audio
cli --> audio_proc
power_mgmt --> sample_audio
power_mgmt --> sample_env
power_mgmt --> cloud

@enduml
