@startuml
skinparam defaultFontSize 36

component "EASNFW-CLOUD" as cloud_comp {
    component "SPIS" as spis
    component "EASNFW-SENSOR" as sensor_comm
    component "log" as log
    component "cloud" as cloud
    component "LTE-M" as ltem
    component "HTTP" as http
    component "external storage" as ext_storage
    component "SPIM" as spim
    component "self-test" as self_test
    component "power management" as power_mgmt
}

[EASNFW-SENSOR] as sensor
[External flash] as ext_flash
[Host PC] as host_pc
[Cloud] as cloud_platform

spis <--> sensor : SPI
spis --> sensor_comm
sensor_comm --> cloud
cloud --> http
http --> ltem
ltem <--> cloud_platform : HTTP over LTE-M
cloud --> ext_storage
ext_storage --> spim
spim <--> ext_flash : SPI
log --> host_pc : Serial-USB
self_test --> spis
self_test --> sensor_comm
self_test --> cloud
self_test --> ltem
self_test --> http
self_test --> ext_storage
self_test --> spim
power_mgmt --> cloud
power_mgmt --> ltem

@enduml
