CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_BACKEND_UART=y
CONFIG_PRINTK=y

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_THREAD_NAME=y
CONFIG_ASSERT=y

CONFIG_I2S=y
CONFIG_I2S_NRFX=y
CONFIG_I2S_LOG_LEVEL_INF=y

CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_SDMMC_SUBSYS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_MAX_LFN=64

CONFIG_MIC_TESTBED_TRACK_SECONDS=60
CONFIG_MIC_TESTBED_WARMUP_BLOCKS=2
CONFIG_MIC_TESTBED_MIN_ABS_PEAK=128
